params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: ${resolve_default:True,${......fixed_sigma}}
    mlp:
      units: [128, 128]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

#  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_checkpoint: ${...load_checkpoint}} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:IDP,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: ${resolve_default:0.999,${....gamma}}
    tau: ${resolve_default:0.99,${....tau}}
    learning_rate: ${resolve_default:1e-4,${....lr}}
    lr_schedule: ${resolve_default:None,${....lr_schedule}}
    schedule_type: standard
    kl_threshold: ${resolve_default:0.002,${....kl_threshold}}
    score_to_win: 20000
    max_epochs: ${resolve_default:3000,${....max_iterations}}
    save_best_after: ${resolve_default:1500,${....end_epoch}}
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: ${resolve_default:0.003,${....entropy_coef}}
    truncate_grads: False
    e_clip: 0.2
    horizon_length: ${resolve_default:64,${....horizon_length}}
    minibatch_size: ${resolve_default:8192,${....minibatch_size}}
    mini_epochs: ${resolve_default:4,${....mini_epochs}}
    critic_coef: 2
    clip_value: True
    bounds_loss_coef: 0.0001
    player:
      games_num: 7
      n_game_life: 1
      save_mat: ${resolve_default:False,${.....save_mat}}
      show_fig: ${resolve_default:True,${.....show_fig}}
      save_fig: ${resolve_default:False,${.....save_fig}}
      deterministic: True
